name: gsheets
description: A library for working with Google Sheets API.
version: 0.0.1-dev.1
author: alexander <a.marenkov@yahoo.com>
homepage: https://github.com/a-marenkov/gsheets
repository: https://github.com/a-marenkov/gsheets.git
issue_tracker: https://github.com/a-marenkov/gsheets/issues

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.10
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
