name: gsheets
description: A library for working with Google Sheets API.
version: 0.0.1-dev.1
author: alexander <a.marenkov@yahoo.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  googleapis: any
  googleapis_auth: any
  http: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
