name: gsheets
description:
  A library for working with Google Sheets API v4.
  Manage your spreadsheets with gsheets in Dart.
version: 0.2.7
homepage: https://github.com/a-marenkov/gsheets
repository: https://github.com/a-marenkov/gsheets.git
issue_tracker: https://github.com/a-marenkov/gsheets/issues

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12
  http: ^0.12.2
  meta: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
